development:
  adapter: postgresql
  encoding: unicode
  database: tasking_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: tasking_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: tasking_production
  pool: 5
  username: <%= ENV["TASKING_DB_USERNAME"] %>
  password: <%= ENV["TASKING_DB_PASSWORD"] %>
  port: 5433
